// import { Product } from "./types/Product";

// export const sampleProducts: Product[] = [
//   {
//     name: "Nike Slim shirt",
//     slug: "nike-slim-shirt",
//     category: "shirts",
//     image: "../images/p1.jpg",
//     brand: "Nike",
//     price: 120,
//     countInStock: 10,
//     description: "high quality shirt",
//     rating: 4.5,
//     numReviews: 10,
//   },
//   {
//     name: "Adidas fit shirt",
//     slug: "adidas-fit-shirt",
//     category: "shirts",
//     image: "../images/p2.png",
//     brand: "Nike",
//     price: 140,
//     countInStock: 10,
//     description: "high quality shirt",
//     rating: 4.5,
//     numReviews: 10,
//   },
//   {
//     name: "Ben Slim shirt",
//     slug: "ben-slim-shirt",
//     category: "shirts",
//     image: "../images/p3.png",
//     brand: "Nike",
//     price: 120,
//     countInStock: 10,
//     description: "high quality shirt",
//     rating: 4.5,
//     numReviews: 10,
//   },
//   {
//     name: "mike Slim shirt",
//     slug: "mike-slim-shirt",
//     category: "shirts",
//     image: "../images/p4.png",
//     brand: "Nike",
//     price: 120,
//     countInStock: 10,
//     description: "high quality shirt",
//     rating: 4.5,
//     numReviews: 10,
//   },
// ];
